name: server-client
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.12.13=py313hb4c8b1a_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - aom=3.9.1=he0c23c2_0
  - assimp=5.4.3=hf1e84b2_0
  - attrs=25.3.0=pyh71513ae_0
  - blinker=1.9.0=pyhff2d567_0
  - blosc=1.21.6=hfd34d9b_1
  - brotli=1.1.0=h2466b09_3
  - brotli-bin=1.1.0=h2466b09_3
  - brotli-python=1.1.0=py313h5813708_3
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.7.9=h4c7d964_0
  - cairo=1.18.4=h5782bbf_0
  - certifi=2025.6.15=pyhd8ed1ab_0
  - cffi=1.17.1=py313ha7868ed_0
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - click=8.2.1=pyh7428d3b_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.2=py313h1ec8472_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - dash=3.0.4=pyhd8ed1ab_0
  - dav1d=1.2.1=hcfcfb64_0
  - double-conversion=3.3.1=he0c23c2_0
  - embree=4.4.0=ha827246_0
  - expat=2.7.0=he0c23c2_0
  - ffmpeg=7.1.1=gpl_h37769ee_906
  - flask=3.1.1=pyhd8ed1ab_0
  - fmt=11.2.0=h1d4551f_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.58.5=py313hd650c13_0
  - freetype=2.13.3=h57928b3_1
  - fribidi=1.0.10=h8d14728_0
  - frozenlist=1.6.0=py313hfe8c4d2_0
  - gdk-pixbuf=2.42.12=hed59a49_0
  - gl2ps=1.4.2=had7236b_1
  - glew=2.1.0=h39d44d4_2
  - glfw=3.4=hcfcfb64_0
  - graphite2=1.3.14=he0c23c2_0
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=11.2.1=h8796e6f_0
  - hdf4=4.2.15=h5557f11_7
  - hdf5=1.14.6=nompi_hd5d9e70_101
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he0c23c2_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2024.2.1=h57928b3_1083
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jsoncpp=1.9.6=hda1637e_1
  - kiwisolver=1.4.8=py313hf069bd2_1
  - krb5=1.21.3=hdf4eb48_0
  - lame=3.100=hcfcfb64_1003
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libaec=1.1.4=h20038f6_0
  - libblas=3.9.0=32_h641d27c_mkl
  - libboost=1.86.0=hb0986bb_3
  - libbrotlicommon=1.1.0=h2466b09_3
  - libbrotlidec=1.1.0=h2466b09_3
  - libbrotlienc=1.1.0=h2466b09_3
  - libcblas=3.9.0=32_h5e41251_mkl
  - libclang13=20.1.7=default_h6e92b77_0
  - libcurl=8.14.1=h88aaa65_0
  - libdeflate=1.24=h76ddb4d_0
  - libexpat=2.7.0=he0c23c2_0
  - libffi=3.4.6=h537db12_1
  - libfreetype=2.13.3=h57928b3_1
  - libfreetype6=2.13.3=h0b5ce68_1
  - libgcc=15.1.0=h1383e82_3
  - libglib=2.84.2=hbc94333_0
  - libgomp=15.1.0=h1383e82_3
  - libhwloc=2.11.2=default_ha69328c_1001
  - libiconv=1.18=h135ad9c_1
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.0=h2466b09_0
  - liblapack=3.9.0=32_h1aa476e_mkl
  - liblapacke=3.9.0=32_h845c4fa_mkl
  - liblzf=3.6=h2466b09_3
  - liblzma=5.8.1=h2466b09_2
  - liblzma-devel=5.8.1=h2466b09_2
  - libmpdec=4.0.0=h827c3e9_0
  - libnetcdf=4.9.2=nompi_he045f6b_117
  - libogg=1.3.5=h2466b09_1
  - libopus=1.5.2=h2466b09_0
  - libpng=1.6.50=h95bef1e_0
  - librsvg=2.58.4=h5ce5fed_3
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.50.2=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libtheora=1.1.1=hc70643c_1006
  - libtiff=4.7.0=h05922d8_5
  - libusb=1.0.29=h1839187_0
  - libvorbis=1.3.7=h0e60522_0
  - libwebp-base=1.5.0=h3b0e114_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_9
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.8=h442d1da_0
  - libzip=1.11.2=h3135430_0
  - libzlib=1.3.1=h2466b09_2
  - loguru=0.7.3=pyh7428d3b_0
  - lz4-c=1.10.0=h2466b09_1
  - markupsafe=3.0.2=py313hb4c8b1a_1
  - matplotlib-base=3.10.3=py313h81b4f16_0
  - minizip=4.0.10=h9fa1bad_0
  - mkl=2024.2.2=h66d3029_15
  - msgpack-python=1.1.1=py313h1ec8472_0
  - multidict=6.6.3=py313hd650c13_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - narwhals=1.46.0=pyhe01879c_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nlohmann_json=3.12.0=he0c23c2_0
  - numpy=2.3.1=py313ha14762d_0
  - open3d=0.19.0=py313hc270506_4
  - openh264=2.6.0=hb17fa0b_0
  - openjpeg=2.5.3=h4d64b90_0
  - openssl=3.5.1=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - pango=1.56.4=h03d888a_0
  - pcre2=10.45=h99c9b8b_0
  - pillow=11.3.0=py313h641beac_0
  - pip=25.1=pyhc872135_2
  - pixman=0.46.2=had0cd8c_0
  - plotly=6.2.0=pyhd8ed1ab_0
  - proj=9.6.2=h4f671f6_0
  - propcache=0.3.1=py313hb4c8b1a_0
  - pthread-stubs=0.4=h0e40799_1002
  - pugixml=1.15=h372dad0_0
  - pycparser=2.22=pyh29332c3_1
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.13.5=h7de537c_102_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.13=0_cp313
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.9.1=h02ddd7d_1
  - requests=2.32.4=pyhd8ed1ab_0
  - retrying=1.4.0=pyhd8ed1ab_0
  - sdl2=2.32.54=he0c23c2_0
  - sdl3=3.2.16=ha4196fd_0
  - setuptools=78.1.1=py313haa95532_0
  - six=1.17.0=pyhd8ed1ab_0
  - snappy=1.2.1=h500f7fa_1
  - sqlite=3.45.3=h2bbff1b_0
  - svt-av1=3.0.2=he0c23c2_0
  - tbb=2021.13.0=h62715c5_1
  - tinyobjloader=1.0.7=h63175ca_2
  - tk=8.6.13=h2c6b04d_2
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=h57928b3_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - utfcpp=4.0.6=hc1507ef_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h818238b_26
  - vs2015_runtime=14.44.35208=h38c0c73_26
  - vtk-base=9.4.2=py313h1f82e82_1
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=py313haa95532_0
  - win32_setctime=1.2.0=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - wslink=2.3.4=pyhd8ed1ab_0
  - x264=1!164.3095=h8ffe710_2
  - x265=3.5=h2d74725_3
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - xz=5.8.1=h208afaa_2
  - xz-tools=5.8.1=h2466b09_2
  - yarl=1.20.1=py313hb4c8b1a_0
  - zeromq=4.3.5=ha9f60a1_7
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h2466b09_2
  - zstandard=0.23.0=py313ha7868ed_2
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - customtkinter==5.2.2
      - darkdetect==0.8.0
prefix: C:\Users\cm03696\AppData\Local\miniconda3\envs\server-client
